package entities;
// Generated Nov 25, 2018 12:22:15 AM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Comments generated by hbm2java
 */
@Entity
@Table(name="comments"
    ,catalog="thuenha24h"
)
public class Comments  implements java.io.Serializable {


     private Integer id;
     private Poster poster;
     private String comment;
     private String email;
     private String name;
     private Date time;

    public Comments() {
    }

    public Comments(Poster poster, String comment, String email, String name, Date time) {
       this.poster = poster;
       this.comment = comment;
       this.email = email;
       this.name = name;
       this.time = time;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_poster", nullable=false)
    public Poster getPoster() {
        return this.poster;
    }
    
    public void setPoster(Poster poster) {
        this.poster = poster;
    }

    
    @Column(name="comment", nullable=false, length=100)
    public String getComment() {
        return this.comment;
    }
    
    public void setComment(String comment) {
        this.comment = comment;
    }

    
    @Column(name="email", nullable=false, length=50)
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }

    
    @Column(name="name", nullable=false, length=50)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="time", nullable=false, length=10)
    public Date getTime() {
        return this.time;
    }
    
    public void setTime(Date time) {
        this.time = time;
    }




}


