package entities;
// Generated Nov 25, 2018 12:22:15 AM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Images generated by hbm2java
 */
@Entity
@Table(name="images"
    ,catalog="thuenha24h"
)
public class Images  implements java.io.Serializable {


     private Integer id;
     private Poster poster;
     private String name;

    public Images() {
    }

    public Images(Poster poster, String name) {
       this.poster = poster;
       this.name = name;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_poster", nullable=false)
    public Poster getPoster() {
        return this.poster;
    }
    
    public void setPoster(Poster poster) {
        this.poster = poster;
    }

    
    @Column(name="name", nullable=false, length=30)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }




}


